.\" Manpage for freenetis-redirection.
.\" Contact ondrej.fibich@gmail.com.in to correct errors or typos.
.TH man 8 "21 November 2013" "1.0" "freenetis-qos-sync man page"
.SH NAME
freenetis-qos-sync \- QoS policy demon for FreenetIS
.SH SYNOPSIS
freenetis-qos-sync
.SH DESCRIPTION
freenetis-qos-sync demon is a part of FreenetIS QoS and it serves for QoS policy of IS FreenetIS. This script should not be used directly.
.SH OPTIONS
The freenetis-qos-sync should not be run directly. It is commonly managed by an init.d script.
.SH AUTHOR
Michal Kliment <kliment@freenetis.org>, 
Roman Sevcik <sevcik.roman@slfree.net>
